--Datenbank erstellen
--CREATE DATABASE zoo;

--Zootabellen erstellen
--CREATE TABLE IF NOT EXISTS zoo (ZooID INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(50), FoundingYear DATE);
--CREATE TABLE IF NOT EXISTS zookeeper (WorkerID INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(50));
--CREATE TABLE IF NOT EXISTS enclosure (EnclosureID INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(50));
--CREATE TABLE IF NOT EXISTS animal (AnimalID INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(50), Species VARCHAR(50));
--CREATE TABLE IF NOT EXISTS food (EAN INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(50), Unit VARCHAR(5), UnitPrice DOUBLE(10,2));
--CREATE TABLE IF NOT EXISTS animalfood (AnimalID INT PRIMARY KEY, EAN INT PRIMARY KEY);

--Beziehungstabellen erstellen (bei viele zu viele Beziehungen)
--CREATE TABLE IF NOT EXISTS animalfood (AnimalID INT, EAN INT, PRIMARY KEY (AnimalID, EAN));
--CREATE TABLE IF NOT EXISTS worksin (WorkerID INT, EnclosureID INT, PRIMARY KEY (WorkerID, EnclosureID));