USE dcvzoo;

CREATE TABLE IF NOT EXISTS zoo (Name VARCHAR(255) PRIMARY KEY, FoundingYear DATE);
CREATE TABLE IF NOT EXISTS enclosure (EnclosureID INT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(255));
CREATE TABLE IF NOT EXISTS animal (AnimalID INT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(255), Type VARCHAR(255));
CREATE TABLE IF NOT EXISTS food (FoodNumber INT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(255), Unit VARCHAR(255), Price DOUBLE);
CREATE TABLE IF NOT EXISTS zookeeper (ZookeeperID INT PRIMARY KEY AUTO_INCREMENT, FirstName VARCHAR(255), LastName VARCHAR(255));
CREATE TABLE IF NOT EXISTS works_in (ZookeeperID INT, EnclosureID INT, PRIMARY KEY (`ZookeeperID`, `EnclosureID`));
CREATE TABLE IF NOT EXISTS eats (AnimalID INT, FoodNr INT, PRIMARY KEY ('AnimalID', 'FoodNr'));