DROP DATABASE IF EXISTS dcvzoo;
CREATE DATABASE dcvzoo;
USE dcvzoo;

CREATE TABLE IF NOT EXISTS zoo (Name VARCHAR(255) PRIMARY KEY, FoundingYear DATE);
CREATE TABLE IF NOT EXISTS enclosure (EnclosureID INT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(255));
CREATE TABLE IF NOT EXISTS animal (AnimalID INT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(255), Type VARCHAR(255));
CREATE TABLE IF NOT EXISTS food (InvoiceNumber INT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(255), Unit VARCHAR(255), Price DOUBLE);
CREATE TABLE IF NOT EXISTS zookeeper (ZookeeperID INT PRIMARY KEY AUTO_INCREMENT, FirstName VARCHAR(255), LastName VARCHAR(255));
CREATE TABLE IF NOT EXISTS works_in (ID INT PRIMARY KEY, ZookeeperID INT, EnclosureID INT, FOREIGN KEY (ZookeeperID) REFERENCES zookeeper(ZookeeperID), FOREIGN KEY (EnclosureID) REFERENCES enclosure(EnclosureID));
CREATE TABLE IF NOT EXISTS eats (ID INT PRIMARY KEY, AnimalID INT, FoodNr INT, FOREIGN KEY (AnimalID) REFERENCES animal(AnimalID), FOREIGN KEY (FoodNr) REFERENCES food(InvoiceNumber));